image: alpine/java:21.0.1

spec:
  inputs:
    openApiFileName:
      default: "surprize :D"
      description: "this variable represents the file name of the openapi yaml file"

stages:
  - build
  - deploy

build-stage:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew openApiGenerate -P$[[inputs.openApiFileName]="car-module-openapi"

