image: alpine/java:21.0.1

include:
  - 'variable-config.yml'

stages:
  - build
  - publish

build-stage:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew openApiGenerate -P$[[inputs.openApiFileName]="car-module-openapi"
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 2 days

publish-stage:
  stage: publish
  variables:
    ci_JOB_TOKEN_OPEN_API:
      value: default-value
  script:
    - chmod +x ./gradlew
    - ./gradlew ./gradlew publish -Pci_JOB_TOKEN_OPEN_API="$ci_JOB_TOKEN_OPEN_API"

