# https://medium.com/@ramavathvinayak/generate-client-sdks-with-openapi-generator-in-springboot-f9f012e73c0b
# https://www.youtube.com/watch?v=tr5_OWgXDiw - generate library
interfaceOnly: true
useSpringBoot3: true
dateLibrary: java8
useTags: true
skipDefaultInterface: true
useResponseEntity: false
useJakartaEe: true
hideGenerationTimestamp: true
apiPackage: com.generated.code.api
modelPackage: com.generated.code.model
groupId: "test1"
id: "gini"
invokerPackage:  com.generated.code.invoker
artifactId: "gini1"