interfaceOnly: true
useSpringBoot3: true
dateLibrary: java8
useTags: true
skipDefaultInterface: true
useResponseEntity: false
useJakartaEe: true
hideGenerationTimestamp: true
apiPackage: com.generated.code.api
modelPackage: com.generated.code.model