# generator-config.yaml

# Input AsyncAPI document path (can also be provided via CLI)
# input: ./specs/asyncapi/car-module-asyncapi.yaml
# Or if it's in the same directory:
input: car-module-asyncapi.yaml

# Generator specific options
generator:
  # The template you are using (models java is a built-in template)
  # For 'models java', the actual template name is '@asyncapi/java-template'
  # but when using `asyncapi generate models java`, the CLI handles this mapping.
  # So, for model generation, you usually don't need a specific template key here,
  # unless you're using a custom template.
  # However, for clarity or if you were using `asyncapi generate` directly, it would be:
  # template: '@asyncapi/java-template'

  # Output directory (corresponds to -o flag)
  output: ./javagenerated/src/main/java/com/example/asyncapi/model

  # You can specify the 'models' command here if you want to be explicit,
  # but typically you'd use 'asyncapi generate models' on the CLI
  # command: models

  # Options passed directly to the generator's internal template
  templateParams:
    # Corresponds to --packageName
    packageName: com.example.asyncapi.model
    # Corresponds to --javaJackson (boolean flag)
    javaJackson: true
    # Corresponds to --javaConstraints (boolean flag)
    javaConstraints: true
    # Corresponds to --javaArrayType=List
    javaArrayType: List