/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.13/userguide/multi_project_builds.html in the Gradle documentation.
 */

val dynamicRootName: String? = settings.providers.gradleProperty("openApiFileName").orNull

rootProject.name = dynamicRootName ?: "openapi-generator" // this will be the name of the library - the artifactId
//include("typescriptgenerated")
//rootProject.name="openapi-generator"



